# Generated by Django 3.2.7 on 2021-09-02 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('variation', models.CharField(max_length=100)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', related_query_name='recipe', to='drinks.drink')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='recipes', related_query_name='recipe', to='drinks.Ingredient')),
            ],
        ),
    ]
